"""Parametric MiniARC: generality by instantiation, not by a score.

The finite world contains asymmetric binary object bitmaps of sizes 2, 3, 4,
and 5.  The intended transformation is horizontal reflection.

Hypotheses are guarded instances of the *same* transformation schema:

    FlipX(size in S)

where S is a subset of the finite size universe.  `S = all sizes` is the fully
parametric explanation; smaller S are specializations obtained by constraining
the size parameter.

The generality preorder is generated by instantiation/constraint inclusion:

    FlipX(S1) >= FlipX(S2)    iff    S1 superset S2.

There is no numeric cost.  Evidence filters inconsistent hypotheses, and the
undominated consistent hypotheses are returned.

A second experiment adds a genuinely different schema, FlipY, to demonstrate
that the order does not compare unrelated parametric explanations merely to
force a winner.

Run:
    python miniARC/parametric_generality.py
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations

Size = int
Bitmap = tuple[str, ...]
Example = tuple[Bitmap, Bitmap]
SIZES: tuple[Size, ...] = (2, 3, 4, 5)


def flip_x(x: Bitmap) -> Bitmap:
    return tuple(row[::-1] for row in x)


def flip_y(x: Bitmap) -> Bitmap:
    return tuple(reversed(x))


def size_of(x: Bitmap) -> int:
    assert len(x) > 0 and all(len(row) == len(x) for row in x)
    return len(x)


def asymmetric_object(n: int) -> Bitmap:
    """Deterministic n x n bitmap asymmetric under X and Y for n >= 2."""
    rows = [["0"] * n for _ in range(n)]
    # An L-like object plus one offset cell.  This avoids accidental X/Y
    # equivalences in the training examples.
    for r in range(n):
        rows[r][0] = "1"
    for c in range(max(1, n - 1)):
        rows[n - 1][c] = "1"
    if n >= 3:
        rows[1][1] = "1"
    return tuple("".join(row) for row in rows)


@dataclass(frozen=True)
class Hypothesis:
    action: str
    sizes: frozenset[int]

    @property
    def name(self) -> str:
        domain = "AnySize" if self.sizes == frozenset(SIZES) else "{" + ",".join(map(str, sorted(self.sizes))) + "}"
        return f"{self.action}({domain})"

    def run(self, x: Bitmap) -> Bitmap | None:
        if size_of(x) not in self.sizes:
            return None
        if self.action == "FlipX":
            return flip_x(x)
        if self.action == "FlipY":
            return flip_y(x)
        raise ValueError(self.action)


def all_nonempty_size_sets() -> tuple[frozenset[int], ...]:
    out: list[frozenset[int]] = []
    for k in range(1, len(SIZES) + 1):
        out.extend(frozenset(xs) for xs in combinations(SIZES, k))
    return tuple(out)


def hypotheses(actions: tuple[str, ...] = ("FlipX",)) -> tuple[Hypothesis, ...]:
    return tuple(Hypothesis(a, ss) for a in actions for ss in all_nonempty_size_sets())


def covers_evidence(h: Hypothesis, evidence: tuple[Example, ...]) -> bool:
    """A candidate explanation must make a prediction on every observed input."""
    return all(h.run(x) == y for x, y in evidence)


def at_least_as_general(a: Hypothesis, b: Hypothesis) -> bool:
    """Instantiation preorder: only compare hypotheses of the same schema."""
    return a.action == b.action and a.sizes >= b.sizes


def strictly_more_general(a: Hypothesis, b: Hypothesis) -> bool:
    return at_least_as_general(a, b) and not at_least_as_general(b, a)


def preferred(evidence: tuple[Example, ...], hs: tuple[Hypothesis, ...]) -> tuple[Hypothesis, ...]:
    vs = tuple(h for h in hs if covers_evidence(h, evidence))
    return tuple(h for h in vs if not any(strictly_more_general(k, h) for k in vs))


def version_space(evidence: tuple[Example, ...], hs: tuple[Hypothesis, ...]) -> tuple[Hypothesis, ...]:
    return tuple(h for h in hs if covers_evidence(h, evidence))


def show_bitmap(x: Bitmap) -> str:
    return "/".join(x)


def experiment_unique_parametric() -> None:
    """Sizes 2,3,4 are observed; size 5 is not.

    Every FlipX guard containing {2,3,4} fits, including the exact observed
    guard {2,3,4}.  AnySize strictly dominates all of them by dropping the size
    restriction.  The order therefore extrapolates to size 5 *because the
    parametric schema itself contains a free size dimension*.
    """
    train_sizes = (2, 3, 4)
    evidence = tuple((asymmetric_object(n), flip_x(asymmetric_object(n))) for n in train_sizes)
    hs = hypotheses(("FlipX",))
    vs = version_space(evidence, hs)
    best = preferred(evidence, hs)

    print("EXPERIMENT 1: one parametric schema\n")
    print("observed sizes:", train_sizes)
    print("consistent hypotheses:")
    for h in vs:
        print(" ", h.name)
    print("undominated:")
    for h in best:
        print(" *", h.name)

    assert best == (Hypothesis("FlipX", frozenset(SIZES)),)
    unseen = asymmetric_object(5)
    assert best[0].run(unseen) == flip_x(unseen)
    print("prediction on unseen size 5:")
    print(" ", show_bitmap(unseen), "->", show_bitmap(best[0].run(unseen)))


def experiment_incomparable_schemas() -> None:
    """Do not force comparison across genuinely different schemas.

    Use a deliberately X/Y-symmetric training object at one size so both FlipX
    and FlipY fit.  Each has its own AnySize maximal instance.  They remain
    incomparable because instantiation alone provides no cross-schema order.
    """
    symmetric: Bitmap = (
        "1001",
        "0110",
        "0110",
        "1001",
    )
    assert flip_x(symmetric) == symmetric == flip_y(symmetric)
    evidence = ((symmetric, symmetric),)
    hs = hypotheses(("FlipX", "FlipY"))
    best = preferred(evidence, hs)

    print("\nEXPERIMENT 2: incomparable parametric schemas\n")
    print("undominated:")
    for h in best:
        print(" *", h.name)

    expected = {
        Hypothesis("FlipX", frozenset(SIZES)),
        Hypothesis("FlipY", frozenset(SIZES)),
    }
    assert set(best) == expected
    print("result: ambiguity preserved; no total order is invented")


def demo() -> None:
    experiment_unique_parametric()
    experiment_incomparable_schemas()


if __name__ == "__main__":
    demo()
