"""Same finite transformations, different representations, different generality.

This experiment tests the claim that abstraction can improve generalization by
*exposing an instantiation relation*, not merely by shortening programs.

We represent horizontal reflection of n x n objects in two languages:

PIXEL LANGUAGE
    A ground permutation table for each concrete size.  Flip2, Flip3, Flip4
    are unrelated symbols.  The language has no parameter whose substitution
    relates them.

OBJECT LANGUAGE
    FlipX(n), where n is a size parameter.  FlipX(2), FlipX(3), FlipX(4) are
    instances of the common schema FlipX(N).

Both languages compute exactly the same transformation on every represented
training example.  The difference is only their generality structure.

No numeric score is used.  The experiment computes maximal consistent
hypotheses under each representation's substitution preorder.

Run:
    python miniARC/representation_generality.py
"""

from __future__ import annotations

from dataclasses import dataclass

Bitmap = tuple[str, ...]
Example = tuple[Bitmap, Bitmap]
TRAIN_SIZES = (2, 3, 4)
ALL_SIZES = (2, 3, 4, 5)


def flip_x(x: Bitmap) -> Bitmap:
    return tuple(row[::-1] for row in x)


def size_of(x: Bitmap) -> int:
    return len(x)


def object_of_size(n: int) -> Bitmap:
    rows = [["0"] * n for _ in range(n)]
    for r in range(n):
        rows[r][0] = "1"
    for c in range(n - 1):
        rows[n - 1][c] = "1"
    if n >= 3:
        rows[1][1] = "1"
    return tuple("".join(r) for r in rows)


# ---------------------------------------------------------------------------
# Pixel representation: concrete transformations are unrelated atoms.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PixelHypothesis:
    """A finite case table keyed by concrete object size.

    This is intentionally the low-level representation: each case stores a
    separate ground permutation.  There is no variable ranging over size and
    hence no substitution edge from several cases to a common parametric term.
    """

    cases: frozenset[int]

    @property
    def name(self) -> str:
        return "PixelCases{" + ",".join(map(str, sorted(self.cases))) + "}"

    def run(self, x: Bitmap) -> Bitmap | None:
        n = size_of(x)
        if n not in self.cases:
            return None
        # Semantically this is the concrete n-specific pixel permutation.
        return flip_x(x)


def pixel_generality(a: PixelHypothesis, b: PixelHypothesis) -> bool:
    """Only identity is generated by substitution in the ground language.

    Although a larger case table has a larger extensional domain, treating
    arbitrary table union as generalization would add structure not present in
    the ground syntax.  The point of this experiment is precisely that the
    pixel representation lacks a common parametric schema.
    """
    return a == b


# ---------------------------------------------------------------------------
# Object representation: one parametric term with constraints on N.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ObjectHypothesis:
    allowed_sizes: frozenset[int]

    @property
    def name(self) -> str:
        if self.allowed_sizes == frozenset(ALL_SIZES):
            return "FlipX(N)"
        return "FlipX(N | N in {" + ",".join(map(str, sorted(self.allowed_sizes))) + "})"

    def run(self, x: Bitmap) -> Bitmap | None:
        if size_of(x) not in self.allowed_sizes:
            return None
        return flip_x(x)


def object_generality(a: ObjectHypothesis, b: ObjectHypothesis) -> bool:
    """Constraint weakening / instantiation order."""
    return a.allowed_sizes >= b.allowed_sizes


def consistent(h, evidence: tuple[Example, ...]) -> bool:
    return all(h.run(x) == y for x, y in evidence)


def maximal_consistent(hs, evidence, ge):
    vs = tuple(h for h in hs if consistent(h, evidence))
    maxima = []
    for h in vs:
        dominated = False
        for k in vs:
            if h == k:
                continue
            if ge(k, h) and not ge(h, k):
                dominated = True
                break
        if not dominated:
            maxima.append(h)
    return vs, tuple(maxima)


def powerset_nonempty(xs: tuple[int, ...]):
    from itertools import combinations

    for k in range(1, len(xs) + 1):
        for ys in combinations(xs, k):
            yield frozenset(ys)


def show(x: Bitmap) -> str:
    return "/".join(x)


def demo() -> None:
    evidence = tuple((object_of_size(n), flip_x(object_of_size(n))) for n in TRAIN_SIZES)

    print("training transformations are extensionally identical in both languages:")
    for x, y in evidence:
        print(f"  size {size_of(x)}: {show(x)} -> {show(y)}")

    # Pixel candidates include the exact three-case table plus supersets.  They
    # all fit, but the ground-language preorder cannot relate them.
    pixel_hs = tuple(PixelHypothesis(s) for s in powerset_nonempty(ALL_SIZES))
    p_vs, p_max = maximal_consistent(pixel_hs, evidence, pixel_generality)

    print("\nPIXEL REPRESENTATION")
    print("consistent:")
    for h in p_vs:
        print(" ", h.name)
    print("maximal under substitution order:")
    for h in p_max:
        print(" *", h.name)

    # Object candidates denote constraints on a single parametric FlipX(N).
    object_hs = tuple(ObjectHypothesis(s) for s in powerset_nonempty(ALL_SIZES))
    o_vs, o_max = maximal_consistent(object_hs, evidence, object_generality)

    print("\nOBJECT REPRESENTATION")
    print("consistent:")
    for h in o_vs:
        print(" ", h.name)
    print("maximal under substitution/constraint order:")
    for h in o_max:
        print(" *", h.name)

    assert len(p_max) == len(p_vs) == 2  # {2,3,4} and {2,3,4,5}, incomparable ground tables
    assert o_max == (ObjectHypothesis(frozenset(ALL_SIZES)),)

    unseen = object_of_size(5)
    print("\nunseen size 5:")
    print("  object maximal predicts:", show(o_max[0].run(unseen)))
    print("  pixel representation has two maximal consistent explanations:")
    for h in p_max:
        pred = h.run(unseen)
        print("   ", h.name, "->", "undefined" if pred is None else show(pred))

    print("\nresult:")
    print("  same observed behavior, different generality structure")
    print("  object abstraction turns separate ground cases into instances of FlipX(N)")
    print("  the resulting extrapolation is induced by substitution, not by a numeric score")


if __name__ == "__main__":
    demo()
